import { Dimensions, StyleSheet } from "react-native";
import colors from "../../styles/colors";

export default StyleSheet.create({
    container:{
        flex:3,
        justifyContent:"space-between",
        backgroundColor:"black"
    },
    header:{
        fontSize:30,
        color:"white",
        marginBottom:15,
        marginTop:20
    },
    header_border:{
        borderWidth:0.5,
        width:Dimensions.get("window").width-80,
        borderColor:"white"
    },
    header_container:{
        marginBottom:5,
        alignItems:"center",
        justifyContent:"center"
    },
    text_container:{
        marginBottom:0,
        marginTop:10,
        alignItems:"center",
        justifyContent:"center"
    },
    text:{
        color:"#d3d3d3",
        fontSize:20,
        fontStyle:"italic",
        textAlign:"center",
        marginLeft:30,
        marginRight:30

    },
    titles:{
        fontSize:15,
        color:"black",

    },
    input_container:{
        flexDirection:"row",
        alignItems:"center",
        marginLeft:10,
        marginTop:20,
        marginBottom:10
    },
    gender_container:{
        flexDirection:"row",
        marginLeft:10,
        justifyContent:"center",
        alignItems:"center"
    },
    gender_title:{
        fontSize:20,
        color:colors.lightgray
    },
    checkBox:{
        marginRight:7,
        marginLeft:20

    },
    bottom_container:{
        flexDirection:"column",
        marginVertical:50,
        flex:3
    },
    aktivity_container:{
        alignItems:"center",
        justifyContent:"center",
        marginBottom:10,
        marginTop:10
    },
    aktivity_header:{
        color:"white",
        fontSize:20,
        marginBottom:5
    },
    checkAktivity:{
        margin:10,
        borderRadius:10,
        borderWidth:1,
        borderColor:colors.darkgray,
        width:Dimensions.get("window").width-30
    },
    selected_aktivity_text:{
        backgroundColor:"white",
        borderRadius:7,
        color:"black",
        fontSize:15,
        padding:10
    },
    unselected_aktivity_text:{
        backgroundColor:"black",
        borderRadius:20,
        color:colors.lightgray,
        fontSize:15,
        padding:10
    },
    button_çıkış:{
        marginBottom:25
    }
})